name: fluxo_caixa_familiar
description: Sistema de Gerenciamento Financeiro Familiar

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localização
  flutter_localizations:
    sdk: flutter
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Utils
  uuid: ^4.3.3
  crypto: ^3.0.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

